require("dotenv").config();
var createError = require("http-errors");
var express = require("express");
var path = require("path");
var cookieParser = require("cookie-parser");
var logger = require("morgan");
const mongoose = require("mongoose");
mongoose.connect(process.env.MONGO_URI);
const { User, Post } = require("./models");
const indexRouter = require("./routes/index");
const homeRouter = require("./routes/home");
const passport = require("passport");
const LocalStrategy = require("passport-local").Strategy;
const session = require("express-session");
const { body, validationResult } = require("express-validator");
const bcrypt = require("bcryptjs");
var app = express();
app.set("views", path.join(__dirname, "/views"));
app.set("view engine", "pug");
app.use(logger("dev"));
app.use(express.json());
app.use(express.urlencoded({ extended: false }));
app.use(cookieParser());
app.use(express.static(path.join(__dirname, "/public")));
app.use(session({ secret: "cats", saveUninitialized: true, resave: false }));
app.use(passport.initialize());
app.use(passport.session());
app.use("/", indexRouter);
app.use("/home", homeRouter);
module.exports = app;
